### ISSUE TITLE
Wrong name and property of observed data from Cox 1986

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/Cimetidine-Triazolam-DDI#3]
@TWendl 
Drug was administered via intraduodenal infusion.

Respective data contain "IV" -> needs to be renamed:
- Cox 1986 - triazolam control - Triazolam - **IV** - 0.5 mg - Serum - agg. (n=4)
- Cox 1986 - triazolam + cimetidine - Triazolam - **IV** - 0.5 mg - Serum - agg. (n=4)

Respective data have meta property: "Route: IV". Needs to be corrected as well.

**Comment by Yuri05** [comment]
Fixed with #5. Closing
@TWendl Please use e.g. "Fixes #NN" for automatic issue closure.
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
